AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless pipeline for Address Validation with AWS Location Service 

Globals: 
  Function:
    Runtime: python3.7
    MemorySize: 128
    Timeout: 15



Resources: 

#######################################
#  Create an AWS Location PlaceIndex  #
#######################################
  AmazonLocationIndex:  
    Type: AWS::Location::PlaceIndex
    Properties: 
      DataSource: Esri
      #DataSourceConfiguration: 
       # DataSourceConfiguration
      Description: Place index for Amazon Location Service Using Esri
      IndexName: ServerlessAddressValidation
      PricingPlan: RequestBasedUsage

########################################
#  S3 Buckets                          #
########################################

  InputBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "inputbucket-address-validation-${AWS::AccountId}"

  RawBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "rawbucket-address-validation-${AWS::AccountId}"
  ProcessedBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "procbucket-address-validation-${AWS::AccountId}"
  DestinationBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "destbucket-address-validation-${AWS::AccountId}"

########################################
#   Lambda Functions                   #
########################################

  scatter:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: scatterfunction/
      Handler: scatter.lambda_handler
      Description: Takes object inputed to InputBucket, shards into X number of files, and puts those files into the RawBucket
      Environment:
        Variables:
          INPUT_BUCKET: !Sub "inputbucket-address-validation-${AWS::AccountId}"
          RAW_SHARDS_BUCKET: !Sub "rawbucket-address-validation-${AWS::AccountId}"
      Policies:
        - S3ReadPolicy:
            BucketName: !Sub "inputbucket-address-validation-${AWS::AccountId}"
        - S3WritePolicy:
            BucketName: !Sub "rawbucket-address-validation-${AWS::AccountId}"
      Events:
        FileUpload:
          Type: S3
          Properties:
            Bucket: !Ref InputBucket
            Events: s3:ObjectCreated:Put
            Filter: 
              S3Key:
                Rules:
                  - Name: suffix
                    Value: '.csv'

  2waygeocoder:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: 2waygeocoderfunction/
      Handler: 2waygeocoder.lambda_handler
      Description: Takes object from RawDataShards bucket, processes those shards in parrallel, and puts shards into Processed Shards bucket
      MemorySize: 128
      Timeout: 900
      Environment:
        Variables: 
          RAW_SHARDS_BUCKET: !Sub "rawbucket-address-validation-${AWS::AccountId}"
          PROCESSED_SHARDS_BUCKET: !Sub "procbucket-address-validation-${AWS::AccountId}"
          LOCATION_INDEX: !Ref AmazonLocationIndex
      Policies: 
        - S3ReadPolicy:
            BucketName: !Sub "rawbucket-address-validation-${AWS::AccountId}"
        - S3WritePolicy: 
            BucketName: !Sub "procbucket-address-validation-${AWS::AccountId}"
        - Version: '2012-10-17' 
          Statement:
              #The following stanzas are required to invoke nested workflows 
            - Effect: Allow
              Action: 
                - geo:SearchPlaceIndexForText
                - geo:SearchPlaceIndexForPosition
              Resource: "*"
      Events:
        FileUpload:
          Type: S3
          Properties:
            Bucket: !Ref RawBucket
            Events: s3:ObjectCreated:Put

  gather:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: gatherfunction/
      Handler: gather.lambda_handler
      Description: Takes objects from processed data shards once the last file is PUT, appends them together to create a single final dataset
      Environment: 
        Variables:
          PROCESSED_SHARDS_BUCKET: !Sub "procbucket-address-validation-${AWS::AccountId}"
          DESTINATION_BUCKET: !Sub "destbucket-address-validation-${AWS::AccountId}"
      Policies: 
        - S3ReadPolicy:
            BucketName: !Sub "procbucket-address-validation-${AWS::AccountId}"
        - S3WritePolicy:
            BucketName: !Sub "destbucket-address-validation-${AWS::AccountId}"
      Events:
        FileUpload:
          Type: S3
          Properties:
            Bucket: !Ref ProcessedBucket
            Events: s3:ObjectCreated:Put
            Filter: 
              S3Key:
                Rules:
                  - Name: suffix
                    Value: 'LAST.csv'

Outputs:
  InputBucket:
    Value: !Ref InputBucket
    Description: S3 Bucket for .csv file input
  RawBucket:
    Value: !Ref RawBucket
    Description: S3 bucket for output from scatter function
  ProcessedBucket:
    Value: !Ref ProcessedBucket
    Description: S3 bucket for output from 2waygeocoder function, input for gather function
  DestinationBucket:
    Value: !Ref DestinationBucket
    Description: S3 bucket for output from gather function
  FunctionArn:
    Value: scatter
    Description: scatter function ARN
  FunctionArn:
    Value: 2waygeocoder
    Description: 2waygeocoder function ARN
  FunctionArn:
    Value: gather
    Description: gather function ARN
